# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
###
POST http://127.0.0.1:8000/api/v1/tags?neeeame=1&state=111&created_by=test
Accept: application/json

###
GET http://127.0.0.1:8000/api/v1/tags
Accept: application/json

###
GET http://sams.yidian-inc.com/api/v1/infomation/rq_status
Accept: application/json

###
PUT http://127.0.0.1:8000/api/v1/tags/1?name=edit1&state=0&modified_by=edit1
Accept: application/json

###
DELETE http://127.0.0.1:8000/api/v1/tags/1
Accept: application/json

### ARTICLE

###
GET http://127.0.0.1:8000/api/v1/articles?state=1&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6InRlc3QiLCJwYXNzd29yZCI6InRlc3QxMjM0NTYiLCJleHAiOjE1NTA4MzM3MjYsImlzcyI6Imdpbi1ibG9nIn0.p_RBh5aLgdEaqFf6N-p7JTBfU6a-bIozgFyGPO9__9c

###
GET http://127.0.0.1:8000/api/v1/articles/1?token=1234

###
POST http://127.0.0.1:8000/api/v1/articles?tag_id=2&title=test11&desc=test-desc&content=test-content&created_by=test-created&state=1&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6InRlc3QiLCJwYXNzd29yZCI6InRlc3QxMjM0NTYiLCJleHAiOjE1NTA4MzM3MjYsImlzcyI6Imdpbi1ibG9nIn0.p_RBh5aLgdEaqFf6N-p7JTBfU6a-bIozgFyGPO9__9c


###
DELETE http://127.0.0.1:8000/api/v1/articles/1

###
GET http://127.0.0.1:8000/auth?username=test&password=test123456

###