# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
###
POST http://127.0.0.1:8000/api/v1/tags?name=tag1&state=1&created_by=wnajk
Accept: application/json

###
GET http://127.0.0.1:8000/api/v1/tags
Accept: application/json

###
PUT http://127.0.0.1:8000/api/v1/tags/7?name=edit1&state=0&modified_by=edit1
Accept: application/json

###
DELETE http://127.0.0.1:8000/api/v1/tags/7
Accept: application/json

### ARTICLE

###
GET http://127.0.0.1:8000/api/v1/articles?state=1
###
GET http://127.0.0.1:8000/api/v1/articles/8
###
PUT http://127.0.0.1:8000/api/v1/articles/8?tag_id=8&modified_by=change&title=test1111&desc=test-111desc&content=test-content111&created_by=test-created&state=1&cover_image_url=http://127.0.0.1:8000/upload/images/0a694d35f2c3266af09daa1e36ed91bc.png
###
DELETE http://127.0.0.1:8000/api/v1/articles/8

###
GET http://127.0.0.1:8000/auth?username=test&password=test11

###
POST http://127.0.0.1:8000/upload
Accept: multipart/form-data
